/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiCaret: typeof import('~icons/mdi/caret')['default']
    IMdiCaretDown: typeof import('~icons/mdi/caret-down')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiPencilBox: typeof import('~icons/mdi/pencil-box')['default']
    IMdiPlusBox: typeof import('~icons/mdi/plus-box')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    TreeView: typeof import('./src/components/TreeView.vue')['default']
  }
}
